---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
# tasks file for ansible-nginx
- include: main-debian.yml
  when: "ansible_os_family == 'Debian'"
- include: main-centos.yml
  when: "ansible_os_family == 'RedHat'"